openapi: 3.0.1
info:
  title: iwanttogoout
  description: API du serveur de jeu iwanttogoout.
  version: 1.0.0
servers:
- url: http://localhost:8080/api
paths:
  /joueur/create/{name}:
    post:
      summary: Création d'un joueur.
      description: Crée un joueur et récupère ses informations de base (nom, vie et position de départ).
      parameters:
      - name: name
        in: path
        description: Le nom du joueur.
        required: true
        schema:
          type: string
      responses:
        200:
          description: La position du joueur dans la map, sa vie et son nom.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Joueur'
        400:
          description: Impossible de créer le joueur.
          content: {}
  /joueur/delete/{name}:
    delete:
      summary: Suppression d'un joueur.
      description: Supprime un joueur de la map et renvoi une réponse précisant si cela a été possible.
      parameters:
      - name: name
        in: path
        description: Le nom du joueur.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Le joueur a été supprimé.
          content: {}
        404:
          description: Le joueur n'existe pas.
          content: {}
components:
  schemas:
    Joueur:
      required:
      - name
      - position
      - life
      type: object
      properties:
        name:
          type: string
        life:
          type: integer
        position:
          type: string
